[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.82"
hapi = { path = "../hapi", features = ["logger"] }
humantime = "2.1.0"
log = "0.4.21"
zip = { version = "1.2.3", default-features = false, features = ["deflate"] }
